"""
Export utilities for Numdux.
Generates Jupyter notebooks, Python scripts from code cells.
"""

import json
from datetime import datetime
from typing import List, Dict, Any


def export_notebook(code_cells: List[dict], metadata: dict = None) -> str:
    """
    Export code cells as a Jupyter notebook (.ipynb) JSON string.
    
    Args:
        code_cells: List of cell dicts with 'code', 'output', 'agent' keys
        metadata: Dataset metadata for the notebook header
    
    Returns:
        JSON string of the .ipynb notebook
    """
    filename = (metadata or {}).get("filename", "dataset")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build notebook cells
    nb_cells = []

    # Title cell
    nb_cells.append({
        "cell_type": "markdown",
        "id": "numdux_header",
        "metadata": {},
        "source": [
            f"# 🧠 Numdux Analysis — {filename}\n",
            f"\n",
            f"> **Generated by Bro AI** on {now}  \n",
            f"> Dataset: `{filename}`\n",
            f"\n",
            f"---",
        ],
    })

    # Imports cell
    nb_cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "numdux_imports",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Auto-generated by Numdux — edit as needed\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import plotly.express as px\n",
            "import plotly.graph_objects as go\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.preprocessing import LabelEncoder\n",
            "import warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            f"# Load your dataset\n",
            f"# df = pd.read_csv('{filename}')\n",
            f"print(f'Notebook ready — load your dataset as df')",
        ],
    })

    # Convert each code cell
    for i, cell in enumerate(code_cells):
        code = cell.get("code", "")
        agent = cell.get("agent", "BroAI")
        output = cell.get("output", "")
        status = cell.get("status", "pending")

        # Add agent label as comment header if not already present
        if not code.strip().startswith("#"):
            code = f"# ── Generated by {agent} ──\n" + code

        # Build outputs
        outputs = []
        if output and output.strip() and status == "success":
            outputs.append({
                "name": "stdout",
                "output_type": "stream",
                "text": [output],
            })
        elif output and status == "error":
            outputs.append({
                "ename": "Error",
                "evalue": output[:200],
                "output_type": "error",
                "traceback": [output],
            })

        nb_cells.append({
            "cell_type": "code",
            "execution_count": None,
            "id": f"cell_{i:04d}",
            "metadata": {
                "numdux_agent": agent,
                "numdux_status": status,
            },
            "outputs": outputs,
            "source": code.splitlines(keepends=True),
        })

    # Build notebook JSON
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0",
            },
            "numdux": {
                "version": "0.1.0",
                "generated_at": now,
                "dataset": filename,
            },
        },
        "cells": nb_cells,
    }

    return json.dumps(notebook, indent=2)


def export_python_script(code_cells: List[dict], metadata: dict = None) -> str:
    """
    Export code cells as a standalone Python script.
    
    Returns:
        Python source code string
    """
    filename = (metadata or {}).get("filename", "dataset")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f'"""',
        f'Numdux Analysis Script',
        f'Dataset: {filename}',
        f'Generated: {now}',
        f'"""',
        '',
        'import pandas as pd',
        'import numpy as np',
        'import warnings',
        'warnings.filterwarnings("ignore")',
        '',
        f'# Load your dataset',
        f'# df = pd.read_csv("{filename}")',
        '',
        '',
    ]

    for i, cell in enumerate(code_cells):
        agent = cell.get("agent", "BroAI")
        code = cell.get("code", "").strip()
        lines.append(f'# {"─" * 50}')
        lines.append(f'# Section {i+1} — {agent}')
        lines.append(f'# {"─" * 50}')
        lines.append(code)
        lines.append('')
        lines.append('')

    return '\n'.join(lines)
