"""
Report generation utilities for Numdux.
Generates Markdown and HTML reports from analysis results.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
import pandas as pd


def generate_markdown_report(
    df: pd.DataFrame,
    metadata: dict,
    models: list = None,
    insights: list = None,
) -> str:
    """
    Generate a comprehensive Markdown report.
    
    Args:
        df: The dataset
        metadata: Metadata dict from extract_metadata()
        models: List of model result dicts
        insights: Optional list of insight strings
    
    Returns:
        Markdown string
    """
    now = datetime.now().strftime("%B %d, %Y at %H:%M")
    filename = metadata.get("filename", "Unknown")
    quality = metadata.get("quality", {})
    cols_info = metadata.get("columns", {})

    # ── Header ────────────────────────────────────────────────────────────────
    md = f"""# 🧠 Numdux Analysis Report

> **Generated by Bro AI** · {now}  
> Dataset: `{filename}`

---

## 📊 Dataset Overview

| Metric | Value |
|--------|-------|
| File | `{filename}` |
| Rows | {metadata.get('rows', 0):,} |
| Columns | {metadata.get('cols', 0)} |
| Memory | {metadata.get('memory_mb', 0):.3f} MB |
| Generated | {now} |

---

## 🏥 Data Quality Assessment

| Check | Value | Status |
|-------|-------|--------|
| Quality Score | **{quality.get('score', 'N/A')}/100** | {'✅' if quality.get('score', 0) > 75 else '⚠️' if quality.get('score', 0) > 50 else '❌'} |
| Missing Values | {quality.get('missing_count', 0):,} ({quality.get('missing_pct', 0)}%) | {'✅' if quality.get('missing_pct', 0) == 0 else '⚠️'} |
| Duplicate Rows | {quality.get('duplicate_rows', 0):,} ({quality.get('dup_pct', 0)}%) | {'✅' if quality.get('duplicate_rows', 0) == 0 else '⚠️'} |
| Total Cells | {quality.get('total_cells', 0):,} | — |

---

## 🔬 Column Analysis

| Column | Type | Null % | Unique | Sample |
|--------|------|--------|--------|--------|
"""

    for col_name, col_data in list(cols_info.items())[:30]:
        dtype = col_data.get("dtype", "—")
        null_pct = col_data.get("null_pct", 0)
        unique = col_data.get("unique_count", "—")
        sample = str(col_data.get("sample", "—"))[:40]
        null_icon = "⚠️" if null_pct > 20 else "✅" if null_pct == 0 else "·"
        md += f"| `{col_name}` | {dtype} | {null_pct}% {null_icon} | {unique:,} | {sample} |\n"

    if len(cols_info) > 30:
        md += f"\n_...and {len(cols_info) - 30} more columns_\n"

    # ── Numeric Statistics ─────────────────────────────────────────────────────
    num_cols = df.select_dtypes(include="number").columns.tolist()
    if num_cols:
        md += "\n---\n\n## 📐 Numeric Statistics\n\n"
        stats = df[num_cols[:15]].describe().round(4)
        md += stats.to_markdown() + "\n"

    # ── Models ─────────────────────────────────────────────────────────────────
    if models:
        md += "\n---\n\n## 🤖 Model Results\n\n"
        try:
            models_df = pd.DataFrame(models)
            md += models_df.to_markdown(index=False) + "\n"
        except Exception:
            for m in models:
                md += f"- **{m.get('Model', 'Model')}**: {m}\n"

    # ── Insights ──────────────────────────────────────────────────────────────
    if insights:
        md += "\n---\n\n## 💡 Key Insights\n\n"
        for i, insight in enumerate(insights, 1):
            md += f"{i}. {insight}\n"

    # ── Footer ────────────────────────────────────────────────────────────────
    md += f"""
---

## 🛠 Technical Details

- **Analysis Tool**: Numdux v0.1.0
- **Bro AI Engine**: LangGraph Multi-Agent System  
- **Python Libraries**: pandas, numpy, scikit-learn, plotly
- **Timestamp**: {now}

---

*This report was automatically generated by Numdux's Bro AI. 
For questions or custom analysis, use the Numdux chat interface.*
"""

    return md


def generate_html_report(
    df: pd.DataFrame,
    metadata: dict,
    models: list = None,
) -> str:
    """Generate a self-contained HTML report."""
    md_content = generate_markdown_report(df, metadata, models)

    # Wrap in minimal HTML with dark theme
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Numdux Report — {metadata.get('filename', 'Analysis')}</title>
    <style>
        body {{
            font-family: 'Segoe UI', system-ui, sans-serif;
            max-width: 960px;
            margin: 2rem auto;
            padding: 2rem;
            background: #0a0e1a;
            color: #e2e8f0;
            line-height: 1.6;
        }}
        h1 {{ color: #00d4ff; border-bottom: 2px solid #1e2d45; padding-bottom: 0.5rem; }}
        h2 {{ color: #7c3aed; margin-top: 2rem; }}
        table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
        th {{ background: #1a2035; color: #94a3b8; padding: 8px 12px; text-align: left; }}
        td {{ padding: 8px 12px; border-bottom: 1px solid #1e2d45; color: #e2e8f0; }}
        tr:hover td {{ background: #111827; }}
        code {{ background: #111827; padding: 2px 6px; border-radius: 4px; color: #00d4ff; font-size: 0.875rem; }}
        blockquote {{ border-left: 3px solid #00d4ff; padding-left: 1rem; color: #94a3b8; }}
        hr {{ border-color: #1e2d45; }}
    </style>
</head>
<body>
{_md_to_basic_html(md_content)}
</body>
</html>"""
    return html


def _md_to_basic_html(md: str) -> str:
    """Very basic markdown-to-HTML converter for report output."""
    import re
    lines = md.split("\n")
    html_lines = []
    in_table = False
    table_header_done = False

    for line in lines:
        # Headers
        if line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html_lines.append(f"<h1>{line[2:]}</h1>")
        # HR
        elif line.strip() == "---":
            html_lines.append("<hr>")
        # Table rows
        elif line.strip().startswith("|") and "|" in line[1:]:
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if all(set(c.replace("-","").replace(":","").strip()) <= set("-: ") for c in cells):
                # Separator row
                if not in_table:
                    html_lines.append("<table>")
                in_table = True
                table_header_done = True
                continue
            if not in_table:
                html_lines.append("<table>")
                in_table = True
                html_lines.append("<tr>" + "".join(f"<th>{c}</th>" for c in cells) + "</tr>")
            elif not table_header_done:
                html_lines.append("<tr>" + "".join(f"<th>{c}</th>" for c in cells) + "</tr>")
            else:
                html_lines.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
        else:
            if in_table:
                html_lines.append("</table>")
                in_table = False
                table_header_done = False
            # Blockquote
            if line.startswith("> "):
                html_lines.append(f"<blockquote>{line[2:]}</blockquote>")
            # Bold/italic/code inline
            else:
                line = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', line)
                line = re.sub(r'`(.+?)`', r'<code>\1</code>', line)
                line = re.sub(r'\*(.+?)\*', r'<em>\1</em>', line)
                html_lines.append(f"<p>{line}</p>" if line.strip() else "<br>")

    if in_table:
        html_lines.append("</table>")

    return "\n".join(html_lines)
